import type {
  Asset,
  Collection,
  Creator,
  Template,
  ActivityRecord,
  PortfolioStats,
  OwnershipRecord,
  User,
} from "@/types/asset"

// Enhanced mock creators data with more comprehensive profiles
export const creators: Creator[] = [
  {
    id: "1",
    slug: "alex-chen",
    name: "Alex Chen",
    address: "0x1a2b3c4d5e6f7g8h9i0j",
    avatar: "/placeholder.svg?height=120&width=120&text=AC",
    verified: true,
    bio: "Digital artist and creative technologist specializing in abstract compositions and futuristic designs. Pioneer in programmable IP assets with over 5 years of experience in blockchain-based creative works.",
    website: "https://alexchen.art",
    twitter: "https://twitter.com/alexchen_art",
    instagram: "https://instagram.com/alexchen.digital",
    discord: "alexchen#1234",
    joinDate: "January 2023",
    totalAssets: 28,
    totalValue: "156.8 ETH",
    totalSales: 42,
    followers: 12500,
    following: 340,
    collections: ["digital-horizons", "quantum-realms", "abstract-dimensions"],
    specialties: ["Art", "NFT", "Digital Design"],
    location: "San Francisco, CA",
    isActive: true,
  },
  {
    id: "2",
    slug: "maya-rodriguez",
    name: "Maya Rodriguez",
    address: "0x2b3c4d5e6f7g8h9i0j1k",
    avatar: "/placeholder.svg?height=120&width=120&text=MR",
    verified: true,
    bio: "Award-winning audio engineer and composer creating immersive soundscapes for the metaverse. Specializing in spatial audio and interactive music experiences.",
    website: "https://mayamusic.io",
    twitter: "https://twitter.com/maya_sounds",
    instagram: "https://instagram.com/maya_audio",
    joinDate: "February 2023",
    totalAssets: 35,
    totalValue: "89.3 ETH",
    totalSales: 67,
    followers: 8900,
    following: 210,
    collections: ["audio-landscapes", "sonic-journeys", "metaverse-sounds"],
    specialties: ["Audio", "Music", "Sound Design"],
    location: "Barcelona, Spain",
    isActive: true,
  },
  {
    id: "3",
    slug: "dr-sarah-kim",
    name: "Dr. Sarah Kim",
    address: "0x3c4d5e6f7g8h9i0j1k2l",
    avatar: "/placeholder.svg?height=120&width=120&text=SK",
    verified: true,
    bio: "AI researcher and patent attorney with PhD in Computer Science. Leading expert in machine learning innovations and intellectual property protection in the digital age.",
    website: "https://sarahkim.research",
    twitter: "https://twitter.com/dr_sarah_ai",
    joinDate: "March 2023",
    totalAssets: 18,
    totalValue: "234.7 ETH",
    totalSales: 15,
    followers: 21000,
    following: 150,
    collections: ["ai-innovations", "ml-patents", "research-papers"],
    specialties: ["Patent", "Software", "AI Research"],
    location: "Seoul, South Korea",
    isActive: true,
  },
  {
    id: "4",
    slug: "techcorp-labs",
    name: "TechCorp Labs",
    address: "0x4d5e6f7g8h9i0j1k2l3m",
    avatar: "/placeholder.svg?height=120&width=120&text=TC",
    verified: true,
    bio: "Enterprise software development and blockchain solutions company. Leading innovation in decentralized technologies and smart contract development.",
    website: "https://techcorp.labs",
    twitter: "https://twitter.com/techcorp_labs",
    joinDate: "January 2023",
    totalAssets: 45,
    totalValue: "312.5 ETH",
    totalSales: 28,
    followers: 35000,
    following: 80,
    collections: ["blockchain-suite", "enterprise-solutions", "defi-protocols", "smart-contracts"],
    specialties: ["Software", "Patent", "Blockchain"],
    location: "Austin, TX",
    isActive: true,
  },
  {
    id: "5",
    slug: "virtual-architects",
    name: "Virtual Architects",
    address: "0x5e6f7g8h9i0j1k2l3m4n",
    avatar: "/placeholder.svg?height=120&width=120&text=VA",
    verified: true,
    bio: "Pioneering studio designing the future of virtual spaces. Specializing in metaverse architecture, 3D environments, and immersive digital experiences.",
    website: "https://virtualarchitects.space",
    twitter: "https://twitter.com/virtual_arch",
    instagram: "https://instagram.com/virtual_architects",
    joinDate: "April 2023",
    totalAssets: 32,
    totalValue: "178.9 ETH",
    totalSales: 24,
    followers: 18000,
    following: 320,
    collections: ["metaverse-spaces", "virtual-buildings", "3d-environments"],
    specialties: ["Art", "Software", "3D Design"],
    location: "London, UK",
    isActive: true,
  },
  {
    id: "6",
    slug: "neon-collective",
    name: "Neon Collective",
    address: "0x6f7g8h9i0j1k2l3m4n5o",
    avatar: "/placeholder.svg?height=120&width=120&text=NC",
    verified: false,
    bio: "Cyberpunk art collective pushing the boundaries of digital expression. Creating dystopian visions and neon-soaked futures through collaborative digital art.",
    website: "https://neoncollective.art",
    instagram: "https://instagram.com/neon_collective",
    discord: "neoncollective#5678",
    joinDate: "May 2023",
    totalAssets: 41,
    totalValue: "124.6 ETH",
    totalSales: 58,
    followers: 28000,
    following: 450,
    collections: ["cyberpunk-dreams", "neon-nights", "digital-dystopia", "future-noir"],
    specialties: ["Art", "NFT", "Digital Art"],
    location: "Tokyo, Japan",
    isActive: true,
  },
  {
    id: "7",
    slug: "quantum-labs",
    name: "Quantum Labs",
    address: "0x7g8h9i0j1k2l3m4n5o6p",
    avatar: "/placeholder.svg?height=120&width=120&text=QL",
    verified: true,
    bio: "Quantum computing research and development laboratory. Pioneering the next generation of computational technologies and quantum algorithms.",
    website: "https://quantumlabs.tech",
    twitter: "https://twitter.com/quantum_labs",
    joinDate: "February 2023",
    totalAssets: 12,
    totalValue: "287.3 ETH",
    totalSales: 8,
    followers: 15000,
    following: 90,
    collections: ["quantum-innovations", "computational-art"],
    specialties: ["Patent", "Software", "Research"],
    location: "Zurich, Switzerland",
    isActive: true,
  },
  {
    id: "8",
    slug: "digital-renaissance",
    name: "Digital Renaissance",
    address: "0x8h9i0j1k2l3m4n5o6p7q",
    avatar: "/placeholder.svg?height=120&width=120&text=DR",
    verified: true,
    bio: "Art movement bridging classical aesthetics with digital innovation. Creating timeless pieces that honor traditional art while embracing cutting-edge technology.",
    website: "https://digitalrenaissance.gallery",
    twitter: "https://twitter.com/digital_ren",
    instagram: "https://instagram.com/digital_renaissance",
    joinDate: "June 2023",
    totalAssets: 29,
    totalValue: "198.4 ETH",
    totalSales: 36,
    followers: 32000,
    following: 180,
    collections: ["classical-digital", "renaissance-nfts", "timeless-art"],
    specialties: ["Art", "NFT", "Classical Art"],
    location: "Florence, Italy",
    isActive: true,
  },
]

// Enhanced collections data with more variety
export const collections: Collection[] = [
  // Alex Chen's Collections
  {
    id: "digital-horizons",
    slug: "digital-horizons",
    name: "Digital Horizons",
    description:
      "A curated collection of abstract digital artworks exploring the boundaries between reality and imagination, featuring stunning gradients and futuristic compositions.",
    assetCount: 12,
    totalValue: "45.8 ETH",
    creator: "Alex Chen",
    creationDate: "January 2024",
    coverImage: "/digital-horizon-collection.png",
    type: "Art",
  },
  {
    id: "quantum-realms",
    slug: "quantum-realms",
    name: "Quantum Realms",
    description:
      "Exploring the intersection of quantum physics and digital art through mesmerizing visual representations of quantum phenomena.",
    assetCount: 8,
    totalValue: "32.4 ETH",
    creator: "Alex Chen",
    creationDate: "March 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Quantum+Realms",
    type: "Art",
  },
  {
    id: "abstract-dimensions",
    slug: "abstract-dimensions",
    name: "Abstract Dimensions",
    description:
      "Multi-dimensional abstract compositions that challenge perception and explore the concept of space in digital art.",
    assetCount: 8,
    totalValue: "28.6 ETH",
    creator: "Alex Chen",
    creationDate: "May 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Abstract+Dimensions",
    type: "Art",
  },

  // Maya Rodriguez's Collections
  {
    id: "audio-landscapes",
    slug: "audio-landscapes",
    name: "Audio Landscapes",
    description:
      "Immersive soundscapes that paint vivid auditory pictures of imaginary worlds, from serene natural environments to bustling futuristic cities.",
    assetCount: 15,
    totalValue: "38.7 ETH",
    creator: "Maya Rodriguez",
    creationDate: "February 2024",
    coverImage: "/audio-landscape-sound-waves.png",
    type: "Audio",
  },
  {
    id: "sonic-journeys",
    slug: "sonic-journeys",
    name: "Sonic Journeys",
    description:
      "Epic audio adventures that take listeners through emotional and physical landscapes using innovative sound design techniques.",
    assetCount: 10,
    totalValue: "29.1 ETH",
    creator: "Maya Rodriguez",
    creationDate: "April 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Sonic+Journeys",
    type: "Audio",
  },
  {
    id: "metaverse-sounds",
    slug: "metaverse-sounds",
    name: "Metaverse Sounds",
    description: "Spatial audio compositions designed specifically for virtual reality and metaverse experiences.",
    assetCount: 10,
    totalValue: "21.5 ETH",
    creator: "Maya Rodriguez",
    creationDate: "June 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Metaverse+Sounds",
    type: "Audio",
  },

  // Dr. Sarah Kim's Collections
  {
    id: "ai-innovations",
    slug: "ai-innovations",
    name: "AI Innovations",
    description:
      "Cutting-edge artificial intelligence patents and research papers covering breakthrough innovations in machine learning and neural networks.",
    assetCount: 8,
    totalValue: "156.3 ETH",
    creator: "Dr. Sarah Kim",
    creationDate: "January 2024",
    coverImage: "/ai-innovation-neural-network.png",
    type: "Patent",
  },
  {
    id: "ml-patents",
    slug: "ml-patents",
    name: "Machine Learning Patents",
    description:
      "Comprehensive collection of machine learning patents covering algorithms, architectures, and applications.",
    assetCount: 6,
    totalValue: "78.4 ETH",
    creator: "Dr. Sarah Kim",
    creationDate: "March 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=ML+Patents",
    type: "Patent",
  },
  {
    id: "research-papers",
    slug: "research-papers",
    name: "Research Papers",
    description: "Academic research papers and technical documentation on AI and machine learning innovations.",
    assetCount: 4,
    totalValue: "12.8 ETH",
    creator: "Dr. Sarah Kim",
    creationDate: "May 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Research+Papers",
    type: "Document",
  },

  // TechCorp Labs Collections
  {
    id: "blockchain-suite",
    slug: "blockchain-suite",
    name: "Blockchain Suite",
    description:
      "Comprehensive blockchain software solutions for enterprise applications, including smart contracts and DeFi protocols.",
    assetCount: 15,
    totalValue: "89.7 ETH",
    creator: "TechCorp Labs",
    creationDate: "February 2024",
    coverImage: "/blockchain-software-interface.png",
    type: "Software",
  },
  {
    id: "enterprise-solutions",
    slug: "enterprise-solutions",
    name: "Enterprise Solutions",
    description: "Business-grade software solutions designed for large-scale enterprise deployment and integration.",
    assetCount: 12,
    totalValue: "67.2 ETH",
    creator: "TechCorp Labs",
    creationDate: "March 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Enterprise+Solutions",
    type: "Software",
  },
  {
    id: "defi-protocols",
    slug: "defi-protocols",
    name: "DeFi Protocols",
    description: "Decentralized finance protocols and smart contracts for next-generation financial applications.",
    assetCount: 10,
    totalValue: "78.9 ETH",
    creator: "TechCorp Labs",
    creationDate: "April 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=DeFi+Protocols",
    type: "Software",
  },
  {
    id: "smart-contracts",
    slug: "smart-contracts",
    name: "Smart Contracts",
    description: "Audited and optimized smart contracts for various blockchain applications and use cases.",
    assetCount: 8,
    totalValue: "76.7 ETH",
    creator: "TechCorp Labs",
    creationDate: "May 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Smart+Contracts",
    type: "Software",
  },

  // Virtual Architects Collections
  {
    id: "metaverse-spaces",
    slug: "metaverse-spaces",
    name: "Metaverse Spaces",
    description:
      "Architectural designs and 3D environments for virtual worlds, featuring innovative spatial concepts and immersive experiences.",
    assetCount: 14,
    totalValue: "67.8 ETH",
    creator: "Virtual Architects",
    creationDate: "February 2024",
    coverImage: "/metaverse-architecture-virtual-space.png",
    type: "Art",
  },
  {
    id: "virtual-buildings",
    slug: "virtual-buildings",
    name: "Virtual Buildings",
    description: "Detailed architectural models of futuristic buildings designed for virtual reality environments.",
    assetCount: 10,
    totalValue: "54.3 ETH",
    creator: "Virtual Architects",
    creationDate: "April 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Virtual+Buildings",
    type: "Art",
  },
  {
    id: "3d-environments",
    slug: "3d-environments",
    name: "3D Environments",
    description: "Complete 3D environmental designs for games, simulations, and virtual experiences.",
    assetCount: 8,
    totalValue: "56.8 ETH",
    creator: "Virtual Architects",
    creationDate: "June 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=3D+Environments",
    type: "Art",
  },

  // Neon Collective Collections
  {
    id: "cyberpunk-dreams",
    slug: "cyberpunk-dreams",
    name: "Cyberpunk Dreams",
    description:
      "Neon-soaked visions of dystopian futures and cybernetic realities, featuring dark cityscapes and technological aesthetics.",
    assetCount: 16,
    totalValue: "48.9 ETH",
    creator: "Neon Collective",
    creationDate: "February 2024",
    coverImage: "/cyberpunk-city-neon-futuristic-night.png",
    type: "Art",
  },
  {
    id: "neon-nights",
    slug: "neon-nights",
    name: "Neon Nights",
    description:
      "Vibrant nighttime scenes illuminated by neon lights and holographic displays in futuristic urban settings.",
    assetCount: 12,
    totalValue: "36.7 ETH",
    creator: "Neon Collective",
    creationDate: "March 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Neon+Nights",
    type: "Art",
  },
  {
    id: "digital-dystopia",
    slug: "digital-dystopia",
    name: "Digital Dystopia",
    description: "Dark visions of technology-dominated futures exploring themes of surveillance and digital control.",
    assetCount: 8,
    totalValue: "24.1 ETH",
    creator: "Neon Collective",
    creationDate: "May 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Digital+Dystopia",
    type: "Art",
  },
  {
    id: "future-noir",
    slug: "future-noir",
    name: "Future Noir",
    description:
      "Film noir aesthetics reimagined in futuristic settings with dramatic lighting and mysterious atmospheres.",
    assetCount: 5,
    totalValue: "14.9 ETH",
    creator: "Neon Collective",
    creationDate: "July 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Future+Noir",
    type: "Art",
  },

  // Quantum Labs Collections
  {
    id: "quantum-innovations",
    slug: "quantum-innovations",
    name: "Quantum Innovations",
    description:
      "Revolutionary quantum computing patents and algorithms that push the boundaries of computational science.",
    assetCount: 8,
    totalValue: "198.7 ETH",
    creator: "Quantum Labs",
    creationDate: "March 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Quantum+Innovations",
    type: "Patent",
  },
  {
    id: "computational-art",
    slug: "computational-art",
    name: "Computational Art",
    description: "Artistic visualizations of quantum phenomena and computational processes.",
    assetCount: 4,
    totalValue: "88.6 ETH",
    creator: "Quantum Labs",
    creationDate: "May 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Computational+Art",
    type: "Art",
  },

  // Digital Renaissance Collections
  {
    id: "classical-digital",
    slug: "classical-digital",
    name: "Classical Digital",
    description:
      "Classical art masterpieces reimagined through digital mediums, honoring traditional techniques while embracing modern technology.",
    assetCount: 15,
    totalValue: "89.3 ETH",
    creator: "Digital Renaissance",
    creationDate: "March 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Classical+Digital",
    type: "Art",
  },
  {
    id: "renaissance-nfts",
    slug: "renaissance-nfts",
    name: "Renaissance NFTs",
    description:
      "NFT collection inspired by Renaissance masters, featuring digital interpretations of classical compositions and techniques.",
    assetCount: 10,
    totalValue: "67.8 ETH",
    creator: "Digital Renaissance",
    creationDate: "April 2024",
    coverImage: "/abstract-horizon-blue-purple.png",
    type: "NFT",
  },
  {
    id: "timeless-art",
    slug: "timeless-art",
    name: "Timeless Art",
    description:
      "Art pieces that transcend time periods, blending historical aesthetics with contemporary digital techniques.",
    assetCount: 4,
    totalValue: "41.3 ETH",
    creator: "Digital Renaissance",
    creationDate: "June 2024",
    coverImage: "/placeholder.svg?height=400&width=600&text=Timeless+Art",
    type: "Art",
  },
]

// Enhanced assets data with more variety and better distribution
export const assets: Asset[] = [
  // Alex Chen's Assets
  {
    id: "1",
    name: "Abstract Horizon #001",
    creator: "Alex Chen",
    verified: true,
    image: "/abstract-horizon-blue-purple.png",
    collection: "Digital Horizons",
    licenseType: "Creative Commons",
    description:
      "A mesmerizing blend of blue and purple hues creating an abstract horizon that captures the essence of digital infinity.",
    registrationDate: "January 15, 2024",
    value: "3.8 ETH",
    type: "Art",
    templateType: "Digital Art",
    templateId: "digital-art",
    protectionLevel: 95,
    metadata: {
      style: "Abstract",
      medium: "Digital",
      dimensions: "3840x2160",
      colorPalette: ["#4F46E5", "#7C3AED", "#EC4899"],
    },
    owner: "CollectorDAO",
    createdAt: "2024-01-15T10:30:00Z",
    numericValue: 3.8,
  },
  {
    id: "2",
    name: "Quantum Particle Dance",
    creator: "Alex Chen",
    verified: true,
    image: "/placeholder.svg?height=400&width=600&text=Quantum+Particle+Dance",
    collection: "Quantum Realms",
    licenseType: "Creative Commons",
    description:
      "Dynamic visualization of quantum particles in motion, representing the fundamental dance of matter at the subatomic level.",
    registrationDate: "March 10, 2024",
    value: "4.2 ETH",
    type: "Art",
    templateType: "Digital Art",
    templateId: "digital-art",
    protectionLevel: 92,
    metadata: {
      style: "Scientific Visualization",
      medium: "Digital",
      dimensions: "4096x4096",
      animation: "60fps",
    },
    owner: "Alex Chen",
    createdAt: "2024-03-10T14:20:00Z",
    numericValue: 4.2,
  },
  {
    id: "3",
    name: "Dimensional Portal #003",
    creator: "Alex Chen",
    verified: true,
    image: "/placeholder.svg?height=400&width=600&text=Dimensional+Portal",
    collection: "Abstract Dimensions",
    licenseType: "Commercial",
    description: "A gateway between dimensions rendered in stunning abstract geometry and ethereal lighting effects.",
    registrationDate: "May 22, 2024",
    value: "3.6 ETH",
    type: "Art",
    templateType: "Digital Art",
    templateId: "digital-art",
    protectionLevel: 89,
    metadata: {
      style: "Geometric Abstract",
      medium: "Digital",
      dimensions: "3840x2160",
      effects: "Particle Systems",
    },
    owner: "MetaverseDAO",
    createdAt: "2024-05-22T16:45:00Z",
    numericValue: 3.6,
  },

  // Maya Rodriguez's Assets
  {
    id: "4",
    name: "Quantum Music Waves",
    creator: "Maya Rodriguez",
    verified: true,
    image: "/quantum-music-waves.png",
    collection: "Audio Landscapes",
    licenseType: "Commercial",
    description:
      "An innovative audio-visual representation of quantum sound waves, blending science and art in perfect harmony.",
    registrationDate: "February 20, 2024",
    value: "2.8 ETH",
    type: "Audio",
    templateType: "Audio Art",
    templateId: "audio-art",
    protectionLevel: 88,
    metadata: {
      duration: "4:32",
      sampleRate: "96kHz",
      format: "FLAC",
      genre: "Ambient Electronic",
    },
    owner: "Maya Rodriguez",
    createdAt: "2024-02-20T14:15:00Z",
    numericValue: 2.8,
  },
  {
    id: "5",
    name: "Ethereal Journey",
    creator: "Maya Rodriguez",
    verified: true,
    image: "/placeholder.svg?height=400&width=600&text=Ethereal+Journey",
    collection: "Sonic Journeys",
    licenseType: "Creative Commons",
    description:
      "A transcendent audio experience that takes listeners through otherworldly soundscapes and emotional landscapes.",
    registrationDate: "April 15, 2024",
    value: "3.1 ETH",
    type: "Audio",
    templateType: "Audio Art",
    templateId: "audio-art",
    protectionLevel: 91,
    metadata: {
      duration: "7:18",
      sampleRate: "48kHz",
      format: "WAV",
      genre: "Cinematic Ambient",
    },
    owner: "AudioCollective",
    createdAt: "2024-04-15T11:30:00Z",
    numericValue: 3.1,
  },
  {
    id: "6",
    name: "VR Spatial Symphony",
    creator: "Maya Rodriguez",
    verified: true,
    image: "/placeholder.svg?height=400&width=600&text=VR+Spatial+Symphony",
    collection: "Metaverse Sounds",
    licenseType: "Commercial",
    description:
      "Immersive spatial audio composition designed for virtual reality environments with 360-degree sound positioning.",
    registrationDate: "June 8, 2024",
    value: "2.4 ETH",
    type: "Audio",
    templateType: "Spatial Audio",
    templateId: "spatial-audio",
    protectionLevel: 94,
    metadata: {
      duration: "5:45",
      format: "Ambisonic B-Format",
      channels: "360° Spatial",
      vrCompatible: true,
    },
    owner: "VRStudio",
    createdAt: "2024-06-08T09:20:00Z",
    numericValue: 2.4,
  },

  // Dr. Sarah Kim's Assets
  {
    id: "7",
    name: "Neural Network Patent #2024-001",
    creator: "Dr. Sarah Kim",
    verified: true,
    image: "/neural-network-patent.png",
    collection: "AI Innovations",
    licenseType: "Patent",
    description:
      "Revolutionary neural network architecture for enhanced machine learning performance with 40% efficiency improvement.",
    registrationDate: "January 30, 2024",
    value: "28.5 ETH",
    type: "Patent",
    templateType: "Technical Patent",
    templateId: "patent",
    protectionLevel: 99,
    metadata: {
      patentNumber: "US11234567B2",
      filingDate: "2024-01-15",
      inventors: ["Dr. Sarah Kim", "Dr. Michael Chen"],
      claims: 24,
    },
    owner: "Dr. Sarah Kim",
    createdAt: "2024-01-30T09:00:00Z",
    numericValue: 28.5,
  },
  {
    id: "8",
    name: "Quantum ML Algorithm",
    creator: "Dr. Sarah Kim",
    verified: true,
    image: "/placeholder.svg?height=400&width=600&text=Quantum+ML+Algorithm",
    collection: "ML Patents",
    licenseType: "Patent",
    description:
      "Breakthrough quantum machine learning algorithm that leverages quantum computing for exponential speedup.",
    registrationDate: "March 25, 2024",
    value: "35.2 ETH",
    type: "Patent",
    templateType: "Technical Patent",
    templateId: "patent",
    protectionLevel: 98,
    metadata: {
      patentNumber: "US11345678B2",
      filingDate: "2024-03-10",
      inventors: ["Dr. Sarah Kim"],
      claims: 18,
    },
    owner: "QuantumTech Inc",
    createdAt: "2024-03-25T13:45:00Z",
    numericValue: 35.2,
  },

  // TechCorp Labs Assets
  {
    id: "9",
    name: "Blockchain Interface v3.0",
    creator: "TechCorp Labs",
    verified: true,
    image: "/blockchain-software-interface.png",
    collection: "Blockchain Suite",
    licenseType: "MIT",
    description:
      "Next-generation blockchain interface software with enhanced security features and improved user experience.",
    registrationDate: "February 10, 2024",
    value: "12.8 ETH",
    type: "Software",
    templateType: "Software License",
    templateId: "software",
    protectionLevel: 96,
    metadata: {
      version: "3.0.1",
      language: "TypeScript",
      framework: "React",
      license: "MIT",
    },
    owner: "TechCorp Labs",
    createdAt: "2024-02-10T16:45:00Z",
    numericValue: 12.8,
  },
  {
    id: "10",
    name: "DeFi Yield Protocol",
    creator: "TechCorp Labs",
    verified: true,
    image: "/placeholder.svg?height=400&width=600&text=DeFi+Yield+Protocol",
    collection: "DeFi Protocols",
    licenseType: "GPL-3.0",
    description:
      "Advanced DeFi protocol for optimized yield farming with automated risk management and portfolio rebalancing.",
    registrationDate: "April 18, 2024",
    value: "18.7 ETH",
    type: "Software",
    templateType: "Smart Contract",
    templateId: "smart-contract",
    protectionLevel: 97,
    metadata: {
      version: "1.2.0",
      language: "Solidity",
      audited: true,
      gasOptimized: true,
    },
    owner: "DeFiDAO",
    createdAt: "2024-04-18T10:15:00Z",
    numericValue: 18.7,
  },

  // Virtual Architects Assets
  {
    id: "11",
    name: "Metaverse Architecture #001",
    creator: "Virtual Architects",
    verified: true,
    image: "/metaverse-architecture-virtual-space.png",
    collection: "Metaverse Spaces",
    licenseType: "Creative Commons",
    description:
      "Stunning architectural design for virtual spaces, featuring futuristic elements and immersive environments.",
    registrationDate: "February 15, 2024",
    value: "6.4 ETH",
    type: "Art",
    templateType: "3D Design",
    templateId: "3d-design",
    protectionLevel: 87,
    metadata: {
      software: "Blender",
      polyCount: "2.8M",
      textures: "4K PBR",
      format: "FBX",
    },
    owner: "MetaverseDAO",
    createdAt: "2024-02-15T11:20:00Z",
    numericValue: 6.4,
  },
  {
    id: "12",
    name: "Neo-Tokyo Tower",
    creator: "Virtual Architects",
    verified: true,
    image: "/placeholder.svg?height=400&width=600&text=Neo+Tokyo+Tower",
    collection: "Virtual Buildings",
    licenseType: "Commercial",
    description: "Futuristic skyscraper design inspired by Japanese architecture and cyberpunk aesthetics.",
    registrationDate: "April 28, 2024",
    value: "8.9 ETH",
    type: "Art",
    templateType: "3D Architecture",
    templateId: "3d-architecture",
    protectionLevel: 92,
    metadata: {
      software: "Blender + Unreal Engine",
      polyCount: "4.2M",
      textures: "8K PBR",
      lighting: "Real-time Ray Tracing",
    },
    owner: "CyberCity Collective",
    createdAt: "2024-04-28T15:30:00Z",
    numericValue: 8.9,
  },

  // Neon Collective Assets
  {
    id: "13",
    name: "Cyberpunk City #2077",
    creator: "Neon Collective",
    verified: false,
    image: "/cyberpunk-city-neon-futuristic-night.png",
    collection: "Cyberpunk Dreams",
    licenseType: "Creative Commons",
    description:
      "A neon-lit cyberpunk cityscape that captures the essence of a futuristic dystopian world with stunning detail.",
    registrationDate: "February 20, 2024",
    value: "4.1 ETH",
    type: "Art",
    templateType: "Digital Art",
    templateId: "digital-art",
    protectionLevel: 78,
    metadata: {
      style: "Cyberpunk",
      mood: "Dystopian",
      lighting: "Neon",
      era: "2077",
    },
    owner: "CyberCollector",
    createdAt: "2024-02-20T20:30:00Z",
    numericValue: 4.1,
  },
  {
    id: "14",
    name: "Neon Samurai",
    creator: "Neon Collective",
    verified: false,
    image: "/placeholder.svg?height=400&width=600&text=Neon+Samurai",
    collection: "Neon Nights",
    licenseType: "Creative Commons",
    description: "A cybernetic samurai warrior illuminated by neon lights in a rain-soaked Tokyo street.",
    registrationDate: "March 18, 2024",
    value: "3.7 ETH",
    type: "Art",
    templateType: "Character Art",
    templateId: "character-art",
    protectionLevel: 82,
    metadata: {
      style: "Cyberpunk Character",
      medium: "Digital Painting",
      dimensions: "2048x3072",
      theme: "Samurai Cyberpunk",
    },
    owner: "NeonCollector",
    createdAt: "2024-03-18T19:45:00Z",
    numericValue: 3.7,
  },

  // Quantum Labs Assets
  {
    id: "15",
    name: "Quantum Entanglement Protocol",
    creator: "Quantum Labs",
    verified: true,
    image: "/placeholder.svg?height=400&width=600&text=Quantum+Entanglement+Protocol",
    collection: "Quantum Innovations",
    licenseType: "Patent",
    description: "Revolutionary quantum entanglement protocol for secure quantum communication networks.",
    registrationDate: "March 12, 2024",
    value: "45.8 ETH",
    type: "Patent",
    templateType: "Quantum Patent",
    templateId: "quantum-patent",
    protectionLevel: 99,
    metadata: {
      patentNumber: "US11456789B2",
      filingDate: "2024-02-28",
      inventors: ["Dr. Elena Vasquez", "Dr. James Wong"],
      quantumBits: "1024",
    },
    owner: "Quantum Labs",
    createdAt: "2024-03-12T08:30:00Z",
    numericValue: 45.8,
  },

  // Digital Renaissance Assets
  {
    id: "16",
    name: "Digital Mona Lisa Remix",
    creator: "Digital Renaissance",
    verified: true,
    image: "/placeholder.svg?height=400&width=600&text=Digital+Mona+Lisa",
    collection: "Classical Digital",
    licenseType: "Creative Commons",
    description:
      "A stunning digital reinterpretation of Da Vinci's Mona Lisa using modern AI and digital art techniques.",
    registrationDate: "March 15, 2024",
    value: "12.3 ETH",
    type: "Art",
    templateType: "Classical Remix",
    templateId: "classical-remix",
    protectionLevel: 94,
    metadata: {
      originalArtist: "Leonardo da Vinci",
      technique: "AI-Enhanced Digital Painting",
      style: "Renaissance Revival",
      dimensions: "4096x6144",
    },
    owner: "ArtDAO",
    createdAt: "2024-03-15T12:00:00Z",
    numericValue: 12.3,
  },
  {
    id: "17",
    name: "The Birth of Digital Venus",
    creator: "Digital Renaissance",
    verified: true,
    image: "/placeholder.svg?height=400&width=600&text=Digital+Venus",
    collection: "Renaissance NFTs",
    licenseType: "Limited Edition",
    description: "Botticelli's Venus reimagined in a digital realm, emerging from binary code instead of sea foam.",
    registrationDate: "April 22, 2024",
    value: "15.7 ETH",
    type: "NFT",
    templateType: "Limited Edition NFT",
    templateId: "limited-nft",
    protectionLevel: 96,
    metadata: {
      originalArtist: "Sandro Botticelli",
      edition: "1 of 1",
      technique: "Digital Transformation",
      blockchain: "Ethereum",
    },
    owner: "RenaissanceCollector",
    createdAt: "2024-04-22T14:30:00Z",
    numericValue: 15.7,
  },

  // Additional remix assets
  {
    id: "18",
    name: "Quantum Horizon Remix",
    creator: "Digital Renaissance",
    verified: true,
    image: "/abstract-horizon-blue-purple.png",
    collection: "Timeless Art",
    licenseType: "Creative Commons",
    description:
      "A creative remix of Alex Chen's Abstract Horizon, infused with classical Renaissance elements and quantum physics concepts.",
    registrationDate: "June 10, 2024",
    value: "5.2 ETH",
    type: "Art",
    templateType: "Remix Art",
    templateId: "remix-art",
    protectionLevel: 89,
    metadata: {
      originalAsset: "1",
      remixType: "Style Transfer + Physics",
      techniques: ["Classical Composition", "Quantum Visualization"],
      inspiration: "Renaissance Masters + Modern Physics",
    },
    owner: "Digital Renaissance",
    createdAt: "2024-06-10T16:20:00Z",
    numericValue: 5.2,
  },
  {
    id: "19",
    name: "Cyberpunk Audio Landscape",
    creator: "Maya Rodriguez",
    verified: true,
    image: "/cyberpunk-city-neon-futuristic-night.png",
    collection: "Sonic Journeys",
    licenseType: "Creative Commons",
    description:
      "An audio remix inspired by Neon Collective's Cyberpunk City, creating an immersive urban soundscape with electronic beats.",
    registrationDate: "May 15, 2024",
    value: "3.9 ETH",
    type: "Audio",
    templateType: "Audio Remix",
    templateId: "audio-remix",
    protectionLevel: 85,
    metadata: {
      originalAsset: "13",
      remixType: "Audio Interpretation",
      duration: "6:42",
      genre: "Cyberpunk Ambient",
      basedOn: "Cyberpunk City #2077",
    },
    owner: "CyberSounds Collective",
    createdAt: "2024-05-15T11:15:00Z",
    numericValue: 3.9,
  },
  {
    id: "20",
    name: "Architectural Soundscape",
    creator: "Virtual Architects",
    verified: true,
    image: "/metaverse-architecture-virtual-space.png",
    collection: "3D Environments",
    licenseType: "Commercial",
    description:
      "A 3D architectural visualization enhanced with spatial audio design, creating an immersive multi-sensory experience.",
    registrationDate: "July 8, 2024",
    value: "7.8 ETH",
    type: "Art",
    templateType: "Mixed Media",
    templateId: "mixed-media",
    protectionLevel: 91,
    metadata: {
      mediaTypes: ["3D Model", "Spatial Audio"],
      software: "Blender + Wwise",
      experience: "VR Compatible",
      duration: "Interactive",
    },
    owner: "ImmersiveDAO",
    createdAt: "2024-07-08T13:45:00Z",
    numericValue: 7.8,
  },
]

// Templates data
export const templates: Template[] = [
  {
    id: "digital-art",
    name: "Digital Art",
    description: "Perfect for digital artwork, illustrations, and creative visual content",
    type: "Art",
    icon: "🎨",
    popularity: 95,
    features: ["High-resolution support", "Color palette analysis", "Style categorization"],
    suitableFor: ["Digital artists", "Illustrators", "Graphic designers"],
    metadataFields: ["style", "medium", "dimensions", "colorPalette"],
  },
  {
    id: "audio-art",
    name: "Audio Art",
    description: "Designed for music, sound effects, and audio compositions",
    type: "Audio",
    icon: "🎵",
    popularity: 78,
    features: ["Waveform analysis", "Audio fingerprinting", "Format conversion"],
    suitableFor: ["Musicians", "Sound designers", "Audio engineers"],
    metadataFields: ["duration", "sampleRate", "format", "genre"],
  },
  {
    id: "patent",
    name: "Technical Patent",
    description: "Comprehensive protection for technical innovations and inventions",
    type: "Patent",
    icon: "⚗️",
    popularity: 65,
    features: ["Prior art search", "Claims validation", "International filing"],
    suitableFor: ["Inventors", "Research institutions", "Tech companies"],
    metadataFields: ["patentNumber", "filingDate", "inventors", "claims"],
  },
  {
    id: "software",
    name: "Software License",
    description: "Protect your software code, algorithms, and digital solutions",
    type: "Software",
    icon: "💻",
    popularity: 82,
    features: ["Code analysis", "License compatibility", "Version tracking"],
    suitableFor: ["Developers", "Software companies", "Open source projects"],
    metadataFields: ["version", "language", "framework", "license"],
  },
  {
    id: "3d-design",
    name: "3D Design",
    description: "For 3D models, architectural designs, and virtual environments",
    type: "Art",
    icon: "🏗️",
    popularity: 71,
    features: ["3D model validation", "Texture analysis", "Polygon optimization"],
    suitableFor: ["3D artists", "Architects", "Game developers"],
    metadataFields: ["software", "polyCount", "textures", "format"],
  },
  {
    id: "nft",
    name: "NFT Collection",
    description: "For non-fungible tokens and digital collectibles",
    type: "NFT",
    icon: "💎",
    popularity: 88,
    features: ["Blockchain verification", "Rarity analysis", "Metadata validation"],
    suitableFor: ["NFT creators", "Digital artists", "Collectors"],
    metadataFields: ["blockchain", "tokenId", "rarity", "edition"],
  },
  {
    id: "remix-art",
    name: "Remix Art",
    description: "For derivative works and creative remixes of existing assets",
    type: "Art",
    icon: "🔄",
    popularity: 43,
    features: ["Original asset linking", "Attribution tracking", "Remix analytics"],
    suitableFor: ["Remix artists", "Collaborators", "Creative communities"],
    metadataFields: ["originalAsset", "remixType", "techniques", "inspiration"],
  },
]

// Activity records
export const activityRecords: ActivityRecord[] = [
  {
    id: "1",
    type: "creation",
    assetId: "1",
    assetName: "Abstract Horizon #001",
    user: "Alex Chen",
    timestamp: "2024-01-15T10:30:00Z",
    details: "Created new digital art asset",
  },
  {
    id: "2",
    type: "transfer",
    assetId: "1",
    assetName: "Abstract Horizon #001",
    user: "CollectorDAO",
    timestamp: "2024-01-16T14:20:00Z",
    details: "Transferred from Alex Chen",
  },
  {
    id: "3",
    type: "creation",
    assetId: "4",
    assetName: "Quantum Music Waves",
    user: "Maya Rodriguez",
    timestamp: "2024-02-20T14:15:00Z",
    details: "Created new audio art asset",
  },
  {
    id: "4",
    type: "creation",
    assetId: "7",
    assetName: "Neural Network Patent #2024-001",
    user: "Dr. Sarah Kim",
    timestamp: "2024-01-30T09:00:00Z",
    details: "Filed new AI patent",
  },
  {
    id: "5",
    type: "license",
    assetId: "9",
    assetName: "Blockchain Interface v3.0",
    user: "Enterprise Client",
    timestamp: "2024-02-12T11:30:00Z",
    details: "Licensed software for commercial use",
  },
]

// Portfolio stats
export const portfolioStats: PortfolioStats = {
  totalAssets: 20,
  totalValue: "287.4 ETH",
  createdAssets: 18,
  licensedAssets: 8,
  protectionLevel: 91,
}

// Mock provenance data
export const mockProvenanceData = {
  "1": {
    events: [
      {
        event: "Asset Created",
        from: null,
        to: "Alex Chen",
        date: "2024-01-15",
        transactionHash: "0xabc123...",
        verified: true,
        type: "creation" as const,
      },
      {
        event: "Asset Transferred",
        from: "Alex Chen",
        to: "CollectorDAO",
        date: "2024-01-16",
        transactionHash: "0xdef456...",
        verified: true,
        type: "transfer" as const,
        memo: "Purchased for collection",
      },
    ] as OwnershipRecord[],
  },
}

// Users data
export const users: User[] = [
  {
    address: "0x1a2b3c4d5e6f7g8h9i0j",
    name: "Alex Chen",
    avatar: "/placeholder.svg?height=40&width=40",
    verified: true,
    bio: "Digital artist specializing in abstract and futuristic designs.",
    website: "https://alexchen.art",
    joinDate: "2023-01-15",
  },
  {
    address: "0x2b3c4d5e6f7g8h9i0j1k",
    name: "Maya Rodriguez",
    avatar: "/placeholder.svg?height=40&width=40",
    verified: true,
    bio: "Audio engineer and composer creating immersive soundscapes.",
    website: "https://mayamusic.io",
    joinDate: "2023-02-20",
  },
]

// Helper functions
export function getAssetById(id: string): Asset | undefined {
  return assets.find((asset) => asset.id === id)
}

export function getCollectionBySlug(slug: string): Collection | undefined {
  return collections.find((collection) => collection.slug === slug)
}

export function getCollectionById(id: string): Collection | undefined {
  return collections.find((collection) => collection.id === id)
}

export function getCreatorBySlug(slug: string): Creator | undefined {
  return creators.find((creator) => creator.slug === slug)
}

export function getCreatorByName(name: string): Creator | undefined {
  return creators.find((creator) => creator.name === name)
}

export function getTemplateById(id: string): Template | undefined {
  return templates.find((template) => template.id === id)
}

export function getAssetsByCollection(collectionSlug: string): Asset[] {
  const collection = getCollectionBySlug(collectionSlug)
  if (!collection) return []

  return assets.filter((asset) => {
    const assetCollectionSlug = asset.collection?.toLowerCase().replace(/\s+/g, "-")
    return assetCollectionSlug === collectionSlug
  })
}

export function getAssetsByCreator(creatorName: string): Asset[] {
  return assets.filter((asset) => asset.creator === creatorName)
}

export function getCollectionsByCreator(creatorName: string): Collection[] {
  return collections.filter((collection) => collection.creator === creatorName)
}

export function getAssetProvenance(assetId: string) {
  return mockProvenanceData[assetId as keyof typeof mockProvenanceData]
}

export function getUserByAddress(address: string): User | undefined {
  return users.find((user) => user.address === address)
}

export function getRemixAssetsByCreator(creatorName: string): Asset[] {
  return assets.filter(
    (asset) => asset.creator === creatorName && (asset.templateType === "Remix Art" || asset.metadata?.originalAsset),
  )
}

// Legacy exports for backward compatibility
export const mockAssets = assets
export const mockCollections = collections
export const mockCreators = creators
export const mockTemplates = templates
export const mockActivityRecords = activityRecords
export const mockPortfolioStats = portfolioStats
export const mockUsers = users

// Export all data as default
export default {
  assets,
  collections,
  creators,
  templates,
  activityRecords,
  portfolioStats,
  users,
  mockProvenanceData,
}
