import {
	CreatedAsset,
	AssetType,
} from '@/components/created-assets/created-assets';

// Mock data for testing the Created Assets component
export const mockCreatedAssets: CreatedAsset[] = [
	{
		id: '1',
		tokenId: '1',
		name: 'Quantum Computing Algorithm',
		description:
			'A revolutionary quantum computing algorithm for optimizing blockchain transactions',
		image: '/placeholder.svg',
		assetType: 'Software' as AssetType,
		symbol: 'QCA',
		preview: 'Algorithm preview...',
		createdAt: '2024-01-15T10:30:00Z',
		contractAddress: '0x123...',
		tokenURI: 'ipfs://QmTest1',
		attributes: [
			{ trait_type: 'Complexity', value: 'High' },
			{ trait_type: 'Field', value: 'Quantum Computing' },
		],
		metadata: {
			author: '0x742d35Cc6e7C0532c8745bCf1c6dCf9aB51c0Ca2',
			version: '2.1',
			license: 'MIT',
		},
		blockchain: 'Starknet',
		tokenStandard: 'ERC721',
		isActive: true,
		lastUpdated: '2024-01-16T14:20:00Z',
	},
	{
		id: '2',
		tokenId: '2',
		name: 'Digital Sunrise',
		description:
			'A beautiful digital artwork capturing the essence of dawn over a cyberpunk city',
		image: '/background.jpg',
		assetType: 'Artwork' as AssetType,
		createdAt: '2024-01-10T09:15:00Z',
		contractAddress: '0x123...',
		tokenURI: 'ipfs://QmTest2',
		attributes: [
			{ trait_type: 'Style', value: 'Cyberpunk' },
			{ trait_type: 'Colors', value: 'Warm' },
			{ trait_type: 'Medium', value: 'Digital' },
		],
		metadata: {
			author: '0x742d35Cc6e7C0532c8745bCf1c6dCf9aB51c0Ca2',
			version: '1.0',
			license: 'Creative Commons',
		},
		blockchain: 'Starknet',
		tokenStandard: 'ERC721',
		isActive: true,
		lastUpdated: '2024-01-10T09:15:00Z',
	},
	{
		id: '3',
		tokenId: '3',
		name: 'Neural Network Patent',
		description:
			'Patent for an innovative neural network architecture for image recognition',
		image: '/placeholder.svg',
		assetType: 'Patent' as AssetType,
		createdAt: '2024-01-08T16:45:00Z',
		contractAddress: '0x123...',
		tokenURI: 'ipfs://QmTest3',
		attributes: [
			{ trait_type: 'Classification', value: 'US Patent' },
			{ trait_type: 'Filed', value: '2024' },
		],
		metadata: {
			author: '0x742d35Cc6e7C0532c8745bCf1c6dCf9aB51c0Ca2',
			version: '1.0',
			license: 'Patent Protection',
		},
		blockchain: 'Starknet',
		tokenStandard: 'ERC721',
		isActive: true,
		lastUpdated: '2024-01-08T16:45:00Z',
	},
	{
		id: '4',
		tokenId: '4',
		name: 'Epic Story Chapter 1',
		description:
			'The first chapter of an epic sci-fi story set in the year 3000',
		image: '/placeholder.svg',
		assetType: 'Story Chapter' as AssetType,
		createdAt: '2024-01-05T11:20:00Z',
		contractAddress: '0x123...',
		tokenURI: 'ipfs://QmTest4',
		attributes: [
			{ trait_type: 'Genre', value: 'Science Fiction' },
			{ trait_type: 'Chapter', value: '1' },
			{ trait_type: 'Word Count', value: '5000' },
		],
		metadata: {
			author: '0x742d35Cc6e7C0532c8745bCf1c6dCf9aB51c0Ca2',
			version: '1.0',
			license: 'Copyright',
		},
		blockchain: 'Starknet',
		tokenStandard: 'ERC721',
		isActive: true,
		lastUpdated: '2024-01-05T11:20:00Z',
	},
	{
		id: '5',
		tokenId: '5',
		name: 'AI Music Composition',
		description: 'An original music composition created with AI assistance',
		image: '/placeholder.svg',
		assetType: 'Music' as AssetType,
		createdAt: '2024-01-03T13:10:00Z',
		contractAddress: '0x123...',
		tokenURI: 'ipfs://QmTest5',
		attributes: [
			{ trait_type: 'Duration', value: '3:45' },
			{ trait_type: 'Genre', value: 'Electronic' },
			{ trait_type: 'AI Assisted', value: 'Yes' },
		],
		metadata: {
			author: '0x742d35Cc6e7C0532c8745bCf1c6dCf9aB51c0Ca2',
			version: '1.0',
			license: 'Creative Commons',
		},
		blockchain: 'Starknet',
		tokenStandard: 'ERC721',
		isActive: true,
		lastUpdated: '2024-01-03T13:10:00Z',
	},
	{
		id: '6',
		tokenId: '6',
		name: 'Innovation Token',
		description:
			'A utility token representing innovation credits in the ecosystem',
		image: '/placeholder.svg',
		assetType: 'IP Token' as AssetType,
		symbol: 'INNOV',
		createdAt: '2024-01-01T08:00:00Z',
		contractAddress: '0x123...',
		tokenURI: 'ipfs://QmTest6',
		attributes: [
			{ trait_type: 'Type', value: 'Utility' },
			{ trait_type: 'Supply', value: '1000000' },
		],
		metadata: {
			author: '0x742d35Cc6e7C0532c8745bCf1c6dCf9aB51c0Ca2',
			version: '1.0',
			license: 'MIT',
		},
		blockchain: 'Starknet',
		tokenStandard: 'ERC20',
		isActive: true,
		lastUpdated: '2024-01-01T08:00:00Z',
	},
	{
		id: '7',
		tokenId: '7',
		name: 'GPT-4 Alternative Model',
		description: 'An open-source language model alternative to GPT-4',
		image: '/placeholder.svg',
		assetType: 'AI Model' as AssetType,
		createdAt: '2023-12-28T15:30:00Z',
		contractAddress: '0x123...',
		tokenURI: 'ipfs://QmTest7',
		attributes: [
			{ trait_type: 'Parameters', value: '175B' },
			{ trait_type: 'Training Data', value: 'Public Domain' },
			{ trait_type: 'License', value: 'Apache 2.0' },
		],
		metadata: {
			author: '0x742d35Cc6e7C0532c8745bCf1c6dCf9aB51c0Ca2',
			version: '1.0',
			license: 'Apache 2.0',
		},
		blockchain: 'Starknet',
		tokenStandard: 'ERC721',
		isActive: true,
		lastUpdated: '2023-12-28T15:30:00Z',
	},
	{
		id: '8',
		tokenId: '8',
		name: 'Research Publication: Blockchain Scalability',
		description: 'Academic paper on novel approaches to blockchain scalability',
		image: '/placeholder.svg',
		assetType: 'Publication' as AssetType,
		createdAt: '2023-12-25T12:00:00Z',
		contractAddress: '0x123...',
		tokenURI: 'ipfs://QmTest8',
		attributes: [
			{ trait_type: 'Pages', value: '25' },
			{ trait_type: 'Citations', value: '12' },
			{ trait_type: 'Impact Factor', value: 'High' },
		],
		metadata: {
			author: '0x742d35Cc6e7C0532c8745bCf1c6dCf9aB51c0Ca2',
			version: '1.0',
			license: 'Academic License',
		},
		blockchain: 'Starknet',
		tokenStandard: 'ERC721',
		isActive: true,
		lastUpdated: '2023-12-25T12:00:00Z',
	},
	{
		id: '9',
		tokenId: '9',
		name: 'Tokenized Real Estate',
		description: 'Fractional ownership of a commercial real estate property',
		image: '/placeholder.svg',
		assetType: 'RWA' as AssetType,
		createdAt: '2023-12-20T10:00:00Z',
		contractAddress: '0x123...',
		tokenURI: 'ipfs://QmTest9',
		attributes: [
			{ trait_type: 'Property Type', value: 'Commercial' },
			{ trait_type: 'Value', value: '$2.5M' },
			{ trait_type: 'Location', value: 'New York' },
		],
		metadata: {
			author: '0x742d35Cc6e7C0532c8745bCf1c6dCf9aB51c0Ca2',
			version: '1.0',
			license: 'Property Rights',
		},
		blockchain: 'Starknet',
		tokenStandard: 'ERC1155',
		isActive: true,
		lastUpdated: '2023-12-20T10:00:00Z',
	},
	{
		id: '10',
		tokenId: '10',
		name: 'Educational Video Series',
		description: 'A comprehensive video series on blockchain development',
		image: '/placeholder.svg',
		assetType: 'Video' as AssetType,
		createdAt: '2023-12-15T14:30:00Z',
		contractAddress: '0x123...',
		tokenURI: 'ipfs://QmTest10',
		attributes: [
			{ trait_type: 'Duration', value: '5 hours' },
			{ trait_type: 'Episodes', value: '10' },
			{ trait_type: 'Level', value: 'Intermediate' },
		],
		metadata: {
			author: '0x742d35Cc6e7C0532c8745bCf1c6dCf9aB51c0Ca2',
			version: '1.0',
			license: 'Educational License',
		},
		blockchain: 'Starknet',
		tokenStandard: 'ERC721',
		isActive: false, // This one is inactive for testing
		lastUpdated: '2023-12-15T14:30:00Z',
	},
];

// Mock stats based on the assets above
export const mockCreatedAssetsStats = {
	totalAssets: mockCreatedAssets.length,
	uniqueTypes: new Set(mockCreatedAssets.map((asset) => asset.assetType)).size,
	mostRecentAsset:
		mockCreatedAssets.sort(
			(a, b) =>
				new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
		)[0]?.name || null,
	activeAssets: mockCreatedAssets.filter((asset) => asset.isActive).length,
	assetsByType: mockCreatedAssets.reduce((acc, asset) => {
		acc[asset.assetType] = (acc[asset.assetType] || 0) + 1;
		return acc;
	}, {} as Record<AssetType, number>),
};
