export const templates = [
  {
    id: "general",
    name: "General Asset",
    icon: "FileText",
    description: "Create a custom intellectual property asset with flexible metadata",
    color: "slate",
    category: "other",
    features: ["Flexible schema", "Friendly forms", "Custom Licensing"],
  },
  {
    id: "audio",
    name: "Audio",
    icon: "Music",
    description: "Register audio files, music, sound effects, podcasts, and other audio content.",
    color: "blue",
    category: "media",
    features: ["Audio details", "Featured Media", "Spotify/Youtube Links"],
  },
  {
    id: "art",
    name: "Art",
    icon: "Palette",
    description: "Register digital or physical artwork, illustrations, paintings, and other visual creations.",
    color: "purple",
    category: "media",
    features: ["Provenance", "Open source", "Transparency"],
  },
  {
    id: "nft",
    name: "NFT",
    icon: "Hexagon",
    description: "Register non-fungible tokens and blockchain-based digital assets.",
    color: "teal",
    category: "blockchain",
    features: ["Token Standard", "Custom metadata", "Interoperability"],
  },
  {
    id: "video",
    name: "Video",
    icon: "Video",
    description: "Register video content, films, animations, and other moving image media.",
    color: "red",
    category: "media",
    features: ["Video details", "Thumbnail setup", "Youtube Links"],
  },
  {
    id: "photography",
    name: "Photography",
    icon: "Camera",
    description: "Register high-quality photography, with camera settings and equipment details.",
    color: "orange",
    category: "media",
    features: ["Camera Metadata", "EXIF Details", "Location Data"],
  },
  {
    id: "software",
    name: "Software",
    icon: "Code",
    description: "Register software applications, code, algorithms, and digital tools.",
    color: "violet",
    category: "tech",
    features: ["Code details", "Code repository"],
  },
  {
    id: "documents",
    name: "Documents",
    icon: "FileText",
    description: "Register written documents, contracts, agreements, and other text-based content.",
    color: "gray",
    category: "legal",
    features: ["Document details", "Version"],
  },
  {
    id: "patents",
    name: "Patents",
    icon: "Award",
    description: "Register patents, inventions, and novel technological solutions.",
    color: "amber",
    category: "legal",
    features: ["Patent details", "Patent classification"],
  },
  {
    id: "posts",
    name: "Posts",
    icon: "MessageSquare",
    description: "Register social media posts, articles, and other short-form content.",
    color: "sky",
    category: "media",
    features: ["Post details", "Wordpress Links", "Censorship Resistance"],
  },
  {
    id: "publications",
    name: "Publications",
    icon: "BookOpen",
    description: "Register books, journals, magazines, and other published materials.",
    color: "indigo",
    category: "media",
    features: ["Publication setup", "Wordpress Links", "Censorship Resistance"],
  },
  {
    id: "rwa",
    name: "Real World Assets",
    icon: "Building",
    description: "Register real-world assets that have been tokenized or digitally represented.",
    color: "emerald",
    category: "blockchain",
    features: ["Asset details", "Proof of Ownership", "Provenance"],
  },
]

export function getTemplateById(id: string) {
  return templates.find((template) => template.id === id) || templates[0]
}

export function getTemplatesByCategory(category: string) {
  return templates.filter((template) => template.category === category)
}
