import type { IPAsset, License } from "./types"

export const ipAssets: IPAsset[] = [
  {
    id: "asset-001",
    name: "Digital Artwork Series: Quantum Realms",
    description: "A collection of digital artworks exploring quantum physics through visual representations.",
    type: "original",
    status: "active",
    createdAt: "2023-10-15T09:30:00Z",
    creator: "Alex Morgan",
    contractAddress: "0x7d2f37829730eD183B55Fd93C6371C79",
    tokenId: "1001",
    image: "/placeholder.svg?height=400&width=400&text=Art",
    licenseCount: 8,
    revenueGenerated: "2.4 ETH",
    lastLicenseDate: "2 days ago",
    assetType: "Art",
    licenseInfo: {
      type: "Creative Commons",
      title: "CC BY-SA",
      version: "4.0",
    },
    terms: {
      commercialUse: "Allowed with license",
      derivativeWorks: "Allowed with attribution",
      attribution: "Required",
      territory: "Worldwide",
      royaltyPercentage: "5%",
      duration: "Perpetual",
    },
  },
  {
    id: "asset-002",
    name: "Music Album: Ethereal Sounds",
    description: "An experimental electronic music album with 12 tracks exploring space and consciousness.",
    type: "original",
    status: "active",
    createdAt: "2023-11-02T14:45:00Z",
    creator: "Sound Wave Studios",
    contractAddress: "0x8b3a9c1dE4F12c8943B89aB60C89f4a5",
    tokenId: "2002",
    image: "/placeholder.svg?height=400&width=400&text=Audio",
    licenseCount: 12,
    revenueGenerated: "1.8 ETH",
    lastLicenseDate: "1 week ago",
    assetType: "Audio",
    licenseInfo: {
      type: "Commercial",
      title: "Music License",
      version: "2.1",
    },
  },
  {
    id: "asset-003",
    name: "3D Model: Future City",
    description: "Highly detailed 3D model of a futuristic cityscape with modular buildings and infrastructure.",
    type: "original",
    status: "active",
    createdAt: "2023-12-05T11:20:00Z",
    creator: "Digital Architects Collective",
    contractAddress: "0x9c4d7e358f2a1B6e4D7c9F5a2E8B3a2F",
    tokenId: "3003",
    image: "/placeholder.svg?height=400&width=400&text=NFT",
    licenseCount: 6,
    revenueGenerated: "3.2 ETH",
    lastLicenseDate: "3 days ago",
    assetType: "NFT",
    licenseInfo: {
      type: "NFT License",
      title: "Commercial Rights",
      version: "1.0",
    },
  },
  {
    id: "asset-004",
    name: "Research Paper: Quantum Computing Applications",
    description: "Academic research paper on practical applications of quantum computing in industry and healthcare.",
    type: "original",
    status: "active",
    createdAt: "2024-01-10T08:15:00Z",
    creator: "Dr. Sarah Chen",
    contractAddress: "0x1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p",
    tokenId: "4004",
    image: "/placeholder.svg?height=400&width=400&text=Doc",
    licenseCount: 3,
    lastLicenseDate: "2 weeks ago",
    assetType: "Publications",
    licenseInfo: {
      type: "Academic",
      title: "Research License",
      version: "1.2",
    },
  },
  {
    id: "asset-005",
    name: "Video Game: Cosmic Explorers",
    description:
      "A space exploration indie game with procedurally generated galaxies and intelligent alien civilizations.",
    type: "original",
    status: "active",
    createdAt: "2024-02-18T16:40:00Z",
    creator: "Indie Game Collective",
    contractAddress: "0x5f4e3d2c1b0a9f8e7d6c5b4a3s2d1f0g",
    tokenId: "5005",
    image: "/placeholder.svg?height=400&width=400&text=Game",
    licenseCount: 5,
    revenueGenerated: "2.1 ETH",
    lastLicenseDate: "5 days ago",
    assetType: "Software",
    licenseInfo: {
      type: "Game License",
      title: "End User License",
      version: "3.0",
    },
  },
  {
    id: "license-001",
    name: "Commercial License - Future City",
    description: "Commercial license for using the Future City 3D model in advertising and marketing.",
    type: "license",
    status: "active",
    createdAt: "2023-12-10T13:25:00Z",
    creator: "Digital Architects Collective",
    contractAddress: "0x9c4d7e358f2a1B6e4D7c9F5a2E8B3a2G",
    tokenId: "3003-L1",
    licenseCount: 0,
    assetType: "NFT",
    licenseInfo: {
      type: "Commercial",
      title: "Advertising Rights",
      version: "1.0",
    },
  },
  {
    id: "license-002",
    name: "Distribution License - Ethereal Sounds",
    description: "License for distribution of the Ethereal Sounds album on streaming platforms.",
    type: "license",
    status: "active",
    createdAt: "2023-11-15T10:30:00Z",
    creator: "Sound Wave Studios",
    contractAddress: "0x8b3a9c1dE4F12c8943B89aB60C89f4a6",
    tokenId: "2002-L1",
    licenseCount: 0,
    assetType: "Audio",
    licenseInfo: {
      type: "Distribution",
      title: "Streaming Rights",
      version: "2.0",
    },
  },
]

const licenses: License[] = [
  {
    id: "license-101",
    name: "Commercial Use - Quantum Realms",
    description: "Commercial usage rights for the Quantum Realms digital artwork series",
    status: "active",
    originalAssetId: "asset-001",
    createdAt: "2024-01-15T09:30:00Z",
    licensee: "Creative Futures Agency",
    licenseeAvatar: "/placeholder.svg?height=40&width=40&text=CF",
    licenseTerms: {
      commercialUse: true,
      derivativeWorks: true,
      attribution: true,
      territory: "Worldwide",
      royaltyPercentage: 5,
      duration: "2 years",
    },
  },
  {
    id: "license-102",
    name: "Exhibition License - Quantum Realms",
    description: "License to exhibit Quantum Realms in physical and virtual galleries",
    status: "active",
    originalAssetId: "asset-001",
    createdAt: "2024-02-02T14:45:00Z",
    licensee: "Digital Art Museum",
    licenseeAvatar: "/placeholder.svg?height=40&width=40&text=DAM",
    licenseTerms: {
      commercialUse: true,
      derivativeWorks: false,
      attribution: true,
      territory: "North America",
      royaltyPercentage: 3,
      duration: "1 year",
    },
  },
  {
    id: "license-103",
    name: "Film Usage - Future City",
    description: "License to use Future City 3D models in film production",
    status: "active",
    originalAssetId: "asset-003",
    createdAt: "2024-01-05T11:20:00Z",
    licensee: "NextGen Studios",
    licenseeAvatar: "/placeholder.svg?height=40&width=40&text=NGS",
    licenseTerms: {
      commercialUse: true,
      derivativeWorks: true,
      attribution: true,
      territory: "Worldwide",
      royaltyPercentage: 7,
      duration: "3 years",
    },
  },
]

export function getAssetById(id: string): IPAsset | undefined {
  return ipAssets.find((asset) => asset.id === id)
}

export function getAssetLicenses(assetId: string): License[] {
  return licenses.filter((license) => license.originalAssetId === assetId)
}

export function getUserLicenses(): License[] {
  // In a real app, this would filter based on the connected user
  return licenses
}
