export const IPFS_URL = process.env.NEXT_PUBLIC_PINATA_HOST!;
export const MIP_CONTRACT = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_MIP!;
export const COLLECTION_CONTRACT_ADDRESS =
  process.env.NEXT_PUBLIC_COLLECTION_CONTRACT_ADDRESS!;

export const EXPLORER_URL = process.env.NEXT_PUBLIC_EXPLORER_URL