import type { Asset, ActivityRecord, PortfolioStats, Collection, Template, IPType } from "@/types/asset"

// Templates data
export const templates: Template[] = [
  {
    id: "template-art-1",
    name: "Digital Artwork",
    description: "Template for digital art, illustrations, and graphic design works",
    type: "Art",
    icon: "palette",
    popularity: 95,
    features: ["High-resolution image support", "Attribution tracking", "Derivative works control"],
    suitableFor: ["Digital artists", "Illustrators", "Graphic designers"],
    metadataFields: ["dimensions", "medium", "style", "colorPalette"],
  },
  {
    id: "template-audio-1",
    name: "Music Track",
    description: "Template for music tracks, songs, and audio compositions",
    type: "Audio",
    icon: "music",
    popularity: 87,
    features: ["Streaming rights management", "Sampling permissions", "Performance tracking"],
    suitableFor: ["Musicians", "Composers", "Sound designers"],
    metadataFields: ["duration", "bpm", "key", "genre", "instruments"],
  },
  {
    id: "template-software-1",
    name: "Software Application",
    description: "Template for software applications, code libraries, and algorithms",
    type: "Software",
    icon: "code",
    popularity: 82,
    features: ["Version control integration", "License enforcement", "API usage tracking"],
    suitableFor: ["Developers", "Software companies", "Open source projects"],
    metadataFields: ["language", "platform", "dependencies", "version"],
  },
  {
    id: "template-nft-1",
    name: "Collectible NFT",
    description: "Template for collectible NFTs with provenance tracking",
    type: "NFT",
    icon: "hexagon",
    popularity: 90,
    features: ["Blockchain verification", "Royalty enforcement", "Provenance tracking"],
    suitableFor: ["Digital artists", "Collectors", "NFT creators"],
    metadataFields: ["blockchain", "tokenId", "edition", "rarity"],
  },
  {
    id: "template-patent-1",
    name: "Technical Patent",
    description: "Template for technical patents and inventions",
    type: "Patent",
    icon: "lightbulb",
    popularity: 75,
    features: ["Prior art analysis", "Claim tracking", "Licensing management"],
    suitableFor: ["Inventors", "R&D departments", "Research institutions"],
    metadataFields: ["claims", "filingDate", "patentClass", "inventors"],
  },
]

// Assets data
export const assets: Asset[] = [
  {
    id: "1",
    name: "Abstract Dimension #312",
    creator: "0xArtist",
    verified: true,
    image: "/background.jpg",
    collection: "Dimensions",
    licenseType: "Creative Commons",
    description: "An abstract digital artwork exploring dimensional concepts with vibrant colors.",
    registrationDate: "January 15, 2025",
    value: "0.85 STRK",
    views: 342,
    type: "Art",
    templateType: "Digital Artwork",
    templateId: "template-art-1",
    protectionLevel: 100,
    metadata: {
      dimensions: "3000x3000px",
      medium: "Digital",
      style: "Abstract",
      colorPalette: "Vibrant",
    },
  },
  {
    id: "2",
    name: "Cosmic Voyager #89",
    creator: "CryptoCreator",
    verified: true,
    image: "/background.jpg",
    collection: "Cosmic Series",
    licenseType: "Commercial Use",
    description: "A journey through cosmic landscapes with ethereal elements and celestial bodies.",
    registrationDate: "February 3, 2025",
    value: "1.2 STRK",
    views: 189,
    type: "Art",
    templateType: "Digital Artwork",
    templateId: "template-art-1",
    protectionLevel: 100,
    metadata: {
      dimensions: "4000x2500px",
      medium: "Digital",
      style: "Sci-Fi",
      colorPalette: "Cosmic",
    },
  },
  {
    id: "3",
    name: "Digital Dreams #567",
    creator: "NFTMaster",
    verified: false,
    image: "/placeholder.svg?height=600&width=400",
    collection: "Dreamscape",
    licenseType: "Personal Use",
    description: "Surreal dreamscapes created through digital manipulation and AI enhancement.",
    registrationDate: "February 18, 2025",
    value: "0.5 STRK",
    views: 127,
    type: "Art",
    templateType: "Digital Artwork",
    templateId: "template-art-1",
    protectionLevel: 100,
    metadata: {
      dimensions: "3500x3500px",
      medium: "Digital/AI",
      style: "Surrealism",
      colorPalette: "Dreamy",
    },
  },
  {
    id: "4",
    name: "Pixel Paradise #42",
    creator: "DigitalArtist",
    verified: true,
    image: "/placeholder.svg?height=450&width=400",
    collection: "Pixel Art",
    licenseType: "Creative Commons",
    description: "Nostalgic pixel art scene depicting a tropical paradise with retro aesthetics.",
    registrationDate: "December 12, 2024",
    value: "0.3 STRK",
    views: 256,
    type: "Art",
    templateType: "Digital Artwork",
    templateId: "template-art-1",
    protectionLevel: 100,
    metadata: {
      dimensions: "128x128px",
      medium: "Pixel Art",
      style: "Retro",
      colorPalette: "Tropical",
    },
  },
  {
    id: "5",
    name: "Neon Genesis #78",
    creator: "0xArtist",
    verified: true,
    image: "/placeholder.svg?height=380&width=400",
    collection: "Neon Collection",
    licenseType: "Commercial Use",
    description: "Cyberpunk-inspired artwork with neon elements and futuristic cityscapes.",
    registrationDate: "March 5, 2025",
    value: "1.5 STRK",
    views: 421,
    type: "Art",
    templateType: "Digital Artwork",
    templateId: "template-art-1",
    protectionLevel: 100,
    metadata: {
      dimensions: "4500x2500px",
      medium: "Digital",
      style: "Cyberpunk",
      colorPalette: "Neon",
    },
  },
  {
    id: "6",
    name: "Quantum Realm #23",
    creator: "QuantumCreator",
    verified: false,
    image: "/placeholder.svg?height=520&width=400",
    collection: "Quantum Series",
    licenseType: "Personal Use",
    description: "Visualization of quantum physics concepts through abstract digital art.",
    registrationDate: "January 30, 2025",
    value: "0.75 STRK",
    views: 98,
    type: "Art",
    templateType: "Digital Artwork",
    templateId: "template-art-1",
    protectionLevel: 100,
    metadata: {
      dimensions: "3000x3000px",
      medium: "Digital",
      style: "Scientific",
      colorPalette: "Quantum",
    },
  },
  {
    id: "7",
    name: "Cyberpunk City #112",
    creator: "CyberArtist",
    verified: true,
    image: "/placeholder.svg?height=480&width=400",
    collection: "Cyberpunk",
    licenseType: "Creative Commons",
    description: "Dystopian urban landscape with high-tech elements and neon-lit streets.",
    registrationDate: "February 25, 2025",
    value: "0.95 STRK",
    views: 312,
    type: "Art",
    templateType: "Digital Artwork",
    templateId: "template-art-1",
    protectionLevel: 100,
    metadata: {
      dimensions: "5000x3000px",
      medium: "Digital",
      style: "Cyberpunk",
      colorPalette: "Neon/Dark",
    },
  },
  {
    id: "8",
    name: "Ethereal Landscape #45",
    creator: "LandscapeArtist",
    verified: true,
    image: "/placeholder.svg?height=420&width=400",
    collection: "Ethereal",
    licenseType: "Commercial Use",
    description: "Dreamlike natural landscapes with otherworldly lighting and atmospheric effects.",
    registrationDate: "March 10, 2025",
    value: "0.65 STRK",
    views: 178,
    type: "Art",
    templateType: "Digital Artwork",
    templateId: "template-art-1",
    protectionLevel: 100,
    metadata: {
      dimensions: "4000x2250px",
      medium: "Digital",
      style: "Landscape",
      colorPalette: "Ethereal",
    },
  },
  {
    id: "9",
    name: "Synthwave Beats Vol. 1",
    creator: "AudioProducer",
    verified: true,
    image: "/background.jpg",
    collection: "Audio Collection",
    licenseType: "Commercial Use",
    description: "A collection of synthwave tracks with retro-futuristic vibes and electronic beats.",
    registrationDate: "March 15, 2025",
    value: "0.4 STRK",
    views: 215,
    type: "Audio",
    templateType: "Music Track",
    templateId: "template-audio-1",
    protectionLevel: 100,
    metadata: {
      duration: "32:45",
      bpm: "120",
      key: "F Minor",
      genre: "Synthwave",
      instruments: "Synthesizers, Drum Machine",
    },
  },
  {
    id: "10",
    name: "Legal Contract Template",
    creator: "LegalEagle",
    verified: true,
    image: "/background.jpg",
    collection: "Legal Documents",
    licenseType: "Commercial Use",
    description: "Professionally drafted legal contract template for business agreements.",
    registrationDate: "March 8, 2025",
    value: "0.25 STRK",
    views: 87,
    type: "Document",
    templateType: "Legal Document",
    templateId: "template-document-1",
    protectionLevel: 100,
    metadata: {
      pages: "24",
      format: "PDF",
      jurisdiction: "International",
      reviewedBy: "Legal Experts",
    },
  },
  {
    id: "11",
    name: "Blockchain Patent #42",
    creator: "TechInnovator",
    verified: true,
    image: "/background.jpg",
    collection: "Tech Patents",
    licenseType: "Commercial Use",
    description: "Patent for a novel blockchain consensus mechanism with improved scalability.",
    registrationDate: "February 28, 2025",
    value: "2.5 STRK",
    views: 132,
    type: "Patent",
    templateType: "Technical Patent",
    templateId: "template-patent-1",
    protectionLevel: 100,
    metadata: {
      claims: "17",
      filingDate: "January 15, 2025",
      patentClass: "G06F 21/64",
      inventors: "Dr. Sarah Chen, Alex Rodriguez",
    },
  },
  {
    id: "12",
    name: "Crypto Trading Algorithm",
    creator: "FinTechDev",
    verified: false,
    image: "/background.jpg",
    collection: "Software Assets",
    licenseType: "Commercial Use",
    description: "Algorithmic trading system for cryptocurrency markets with machine learning optimization.",
    registrationDate: "March 12, 2025",
    value: "1.8 STRK",
    views: 203,
    type: "Software",
    templateType: "Software Application",
    templateId: "template-software-1",
    protectionLevel: 100,
    metadata: {
      language: "Python",
      platform: "Cross-platform",
      dependencies: "TensorFlow, NumPy, Pandas",
      version: "2.1.4",
    },
  },
]

// Activity data
export const recentActivity: ActivityRecord[] = [
  {
    id: "act-1",
    type: "view",
    assetId: "5",
    assetName: "Neon Genesis #78",
    user: "Collector123",
    timestamp: "2 hours ago",
    details: "Viewed asset details",
  },
  {
    id: "act-2",
    type: "license",
    assetId: "1",
    assetName: "Abstract Dimension #312",
    user: "Studio XYZ",
    timestamp: "1 day ago",
    details: "Purchased commercial license",
  },
  {
    id: "act-3",
    type: "transfer",
    assetId: "2",
    assetName: "Cosmic Voyager #89",
    user: "GalleryDAO",
    timestamp: "3 days ago",
    details: "Full ownership transfer",
  },
  {
    id: "act-4",
    type: "creation",
    assetId: "7",
    assetName: "Cyberpunk City #112",
    user: "You",
    timestamp: "5 days ago",
    details: "Created and registered new asset",
  },
  {
    id: "act-5",
    type: "view",
    assetId: "6",
    assetName: "Quantum Realm #23",
    user: "ArtEnthusiast",
    timestamp: "1 week ago",
    details: "Viewed asset details",
  },
]

// Collections data
export const collections: Collection[] = [
  {
    id: "col-1",
    name: "Dimensions",
    description: "A collection of abstract digital artworks exploring dimensional concepts",
    assetCount: 3,
    totalValue: "2.55 STRK",
    creator: "0xArtist",
    creationDate: "December 10, 2024",
    coverImage: "/background.jpg",
    type: "Art",
  },
  {
    id: "col-2",
    name: "Cosmic Series",
    description: "Artworks depicting cosmic landscapes and celestial phenomena",
    assetCount: 2,
    totalValue: "1.95 STRK",
    creator: "CryptoCreator",
    creationDate: "January 15, 2025",
    coverImage: "/background.jpg",
    type: "Art",
  },
  {
    id: "col-3",
    name: "Neon Collection",
    description: "Cyberpunk-inspired artworks with neon aesthetics",
    assetCount: 4,
    totalValue: "3.2 STRK",
    creator: "0xArtist",
    creationDate: "February 5, 2025",
    coverImage: "/placeholder.svg?height=380&width=400",
    type: "Art",
  },
  {
    id: "col-4",
    name: "Audio Collection",
    description: "Music tracks and sound compositions",
    assetCount: 2,
    totalValue: "0.7 STRK",
    creator: "AudioProducer",
    creationDate: "March 1, 2025",
    coverImage: "/background.jpg",
    type: "Audio",
  },
  {
    id: "col-5",
    name: "Tech Patents",
    description: "Technical patents for blockchain and related technologies",
    assetCount: 3,
    totalValue: "5.8 STRK",
    creator: "TechInnovator",
    creationDate: "January 20, 2025",
    coverImage: "/background.jpg",
    type: "Patent",
  },
]

// Calculate portfolio statistics
export const calculatePortfolioStats = (assets: Asset[]): PortfolioStats => {
  const createdAssets = assets.filter((a) => a.creator === "0xArtist").length
  const totalValue =
    assets.reduce((sum, asset) => sum + Number.parseFloat(asset.value.split(" ")[0]), 0).toFixed(2) + " STRK"
  const totalViews = assets.reduce((sum, asset) => sum + asset.views, 0)
  const avgProtectionLevel = Math.round(
    assets.reduce((sum, asset) => sum + (asset.protectionLevel || 0), 0) / assets.length,
  )

  return {
    totalAssets: assets.length,
    totalValue,
    createdAssets,
    licensedAssets: 3,
    recentViews: totalViews,
    protectionLevel: avgProtectionLevel,
  }
}

// Helper functions
export const getAssetsByType = (type: IPType): Asset[] => {
  return assets.filter((asset) => asset.type === type)
}

export const getAssetsByTemplate = (templateId: string): Asset[] => {
  return assets.filter((asset) => asset.templateId === templateId)
}

export const getAssetsByCollection = (collectionName: string): Asset[] => {
  return assets.filter((asset) => asset.collection === collectionName)
}

export const getTemplateById = (templateId: string): Template | undefined => {
  return templates.find((template) => template.id === templateId)
}

export const getAssetById = (assetId: string): Asset | undefined => {
  return assets.find((asset) => asset.id === assetId)
}

export const getCollectionByName = (name: string): Collection | undefined => {
  return collections.find((collection) => collection.name === name)
}

export const getIconForType = (type: IPType): string => {
  const iconMap: Record<IPType, string> = {
    Art: "palette",
    Audio: "music",
    Video: "video",
    Document: "file-text",
    Patent: "lightbulb",
    Trademark: "badge",
    Software: "code",
    NFT: "hexagon",
    Other: "box",
  }

  return iconMap[type] || "box"
}
